version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 3
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 3
    schedule:
      interval: "monthly"
    rebase-strategy: "auto"
    cooldown:
      default-days: 14
      semver-major-days: 28
